### ISSUE TITLE
missing - from urls 

### ISSUE THREAD

**Issue by gurugeek** [loopwerk/Saga#14]
First and foremost thank you for Saga :) Is good to have another swift static site generator. I am migrating my website from Svelte (Sapper) and I managed to get the articles to serve from the root path e.g. domain.com/article-title

The problem is that apparently all URLs/folders in deploy are without the dash. So If I have an article named my-long-title.md
it becomes now mylongtitle.md 

I am not sure if is something I caused with my modifications but I can't find anywhere a function that replaces these tags.  I would be grateful if you could point me in the right direction. Thank you!

**Comment by kevinrenskers** [comment]
Hey, thanks for the kind words and the bug report. There was a problem with the slugify method, which I've fixed and added tests for. Should be good now!

Version 0.22.0 is pushed.
